image:
  file: Dockerfile
  
ports:
  - port: 8001
  
tasks:
  -  init: mkdir /workspace/my-gitpod-ionic-cordova/logs                              &&
           touch /workspace/my-gitpod-ionic-cordova/logs/gitpod-install-log.txt       &&
           mkdir /workspace/my-gitpod-ionic-cordova/android                           &&

           
          
     command: echo "Starting .gitpod.yml installation"              &>>  /workspace/my-gitpod-ionic-cordova/logs/gitpod-install-log.txt       &&  
     
     
     
     
              echo "Install the Android SDK"                         &>>  /workspace/my-gitpod-ionic-cordova/logs/gitpod-install-log.txt      &&                 
              wget https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip                                                       &&     
              unzip sdk-tools-linux-4333796.zip -d android                                                                                    &&            
              rm sdk-tools-linux-4333796.zip                                                                                                  &&     
              ./android/tools/bin/sdkmanager --list                  &>> /workspace/my-gitpod-ionic-cordova/logs/gitpod-install-log.txt       &&     
              yes | ./android/tools/bin/sdkmanager "platform-tools" "build-tools;28.0.3" "platforms;android-28"                               &&             
                
                
                
                
              export ANDROID_SDK_ROOT="/workspace/my-gitpod-ionic-cordova/android/"                                                           &&                        
              export PATH="${PATH}:${ANDROID_SDK_ROOT}tools/:${ANDROID_SDK_ROOT}platform-tools/"                                              &&     
              echo  $ANDROID_SDK_ROOT                                &>> /workspace/my-gitpod-ionic-cordova/logs/gitpod-install-log.txt       &&        
             
          
          
              echo "Starting Apache\n"                               &>>  /workspace/my-gitpod-ionic-cordova/logs/gitpod-install-log.txt      &&   
              apachectl start                                                                                                                 &&
              gp await-port 8001                                                                                                              && 
              gp preview $(gp url 8001)                                                                                                       &&


         
              
              echo "Ending .gitpod.yml installation"                 &>>   /workspace/my-gitpod-ionic-cordova/logs/gitpod-install-log.txt    
              
              
              
              
              
 
