image:
  file: Dockerfile
  
ports:
  - port: 8001
  
tasks:
  -  init: touch logs.txt       &&
           mkdir android        &&

           
          
     command: echo "Starting .gitpod.yml installation\n\n"           &>> /workspace/my-gitpod-cordova/logs.txt  &&  
     
     
     
     
              echo "Install the Android SDK"                         &>> /workspace/my-gitpod-cordova/logs.txt  &&                 
              wget https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip                         &&     
              unzip sdk-tools-linux-4333796.zip -d android                                                      &&            
              rm sdk-tools-linux-4333796.zip                                                                    &&     
              ./android/tools/bin/sdkmanager --list                  &>> /workspace/my-gitpod-cordova/logs.txt  &&     
              yes | ./android/tools/bin/sdkmanager "platform-tools" "build-tools;28.0.3" "platforms;android-28" &&             
                
                
                
                
              export ANDROID_SDK_ROOT="/workspace/my-gitpod-cordova/android/"                                   &&                        
              export PATH="${PATH}:${ANDROID_SDK_ROOT}tools/:${ANDROID_SDK_ROOT}platform-tools/"                &&     
              echo  $ANDROID_SDK_ROOT                                &>> /workspace/my-gitpod-cordova/logs.txt  &&        
             
          
          
              echo "Starting Apache\n"                    &>> /workspace/my-gitpod-dockerfile-cordova/logs.txt  &&   
              apachectl start                                                                                   &&
              gp await-port 8001                                                                                && 
              gp preview $(gp url 8001)                                                                         &&


         
              
              echo "Ending .gitpod.yml installation"                 &>> /workspace/my-gitpod-cordova/logs.txt     
              
              
 
