image:
  file: Dockerfile
  
ports:
  - port: 8001
  
tasks:
  -  command: mkdir /workspace/my-gitpod-ionic-cordova/logs                              &&
              touch /workspace/my-gitpod-ionic-cordova/logs/gitpod-install-log.txt       &&
              mkdir /workspace/my-gitpod-ionic-cordova/android                           &&
       
       
              echo "Starting .gitpod.yml installation" &>>  /workspace/my-gitpod-ionic-cordova/logs/gitpod-install-log.txt  &&  
              
              echo "Set bash files to runable"         &>>  /workspace/my-gitpod-ionic-cordova/logs/gitpod-install-log.txt  &&                 
              chmod +x a01-cordova-create.sh                                                                                &&      
              chmod +x a02-cordova-rebuild.sh                                                                               &&     
              chmod +x a03-android-sdkmanager.sh                                                                            && 
              chmod -R 775 /home/gitpod/.android                                                                            &&
             
          
   
              echo "Installing Android Platforms "     &>>  /workspace/my-gitpod-ionic-cordova/logs/gitpod-install-log.txt  &&  
              export ANDROID_SDK_ROOT=" /home/gitpod/.android"                                                              &&                        
              export PATH="${PATH}:${ANDROID_SDK_ROOT}/tools:${ANDROID_SDK_ROOT}/tools/bin:${ANDROID_SDK_ROOT}/platform-tools"  &&                       
              echo  $PATH                              &>> /workspace/my-gitpod-ionic-cordova/logs/gitpod-install-log.txt   &&   
              yes | sdkmanager "platform-tools" "build-tools;28.0.3" "platforms;android-28"                                 &&       
              sdkmanager --list                        &>> /workspace/my-gitpod-ionic-cordova/logs/gitpod-install-log.txt   &&     
             

          
              echo "Starting Apache"                   &>>  /workspace/my-gitpod-ionic-cordova/logs/gitpod-install-log.txt  &&   
              apachectl start                                                                                               &&
              gp await-port 8001                                                                                            && 
              gp preview $(gp url 8001)                                                                                     &&
              
              
              
              echo "Ending .gitpod.yml installation"  &>>   /workspace/my-gitpod-ionic-cordova/logs/gitpod-install-log.txt    
              
              
     
